# Generated by Django 5.2.6 on 2025-11-25 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('SOC', 'Society'), ('EDU', 'Education'), ('HLT', 'Health'), ('CUL', 'Culture'), ('TEC', 'Technology')], default='SOC', max_length=3)),
                ('rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], default=3)),
                ('labels', models.ManyToManyField(blank=True, related_name='posts', to='labels.label')),
            ],
        ),
        migrations.CreateModel(
            name='PostLabelingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=256)),
                ('labelled_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_labeling_details', to='labels.label')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_labeling_details', to='posts.post')),
            ],
            options={
                'unique_together': {('post', 'label')},
            },
        ),
    ]
