# Generated by Django 5.2.6 on 2025-11-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
        ('posts', '0001_initial'),
        ('reasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='posts', through='reasons.Reason', to='labels.label'),
        ),
    ]
