# Generated by Django 5.2.6 on 2026-01-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_category_remove_post_labels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='covers/nocover.png', upload_to='covers'),
        ),
    ]
