# Generated by Django 5.2.6 on 2025-11-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labelled_because', models.CharField(max_length=256)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seals', to='labels.label')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seals', to='posts.post')),
            ],
        ),
    ]
